# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.PositiveIntegerField(choices=[(1, b'team_level'), (2, b'user_level')], default=0)),
                ('winner', models.CharField(default=None, max_length=200)),
                ('event_info', models.CharField(default=0, max_length=600)),
                ('description', models.TextField(max_length=1000)),
                ('timing', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'game name', max_length=200)),
                ('description', models.TextField(default=b'game desc', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=b'', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveIntegerField(choices=[(1, b'Player'), (2, b'Moderator'), (3, b'Admin')], default=1)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tf2.Team')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tf2.Games'),
        ),
        migrations.AddField(
            model_name='events',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tf2.Team'),
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
