# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2', '0003_auto_20180121_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(1, b'team level'), (2, b'user level')], default=0),
        ),
    ]
