# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2', '0005_auto_20180121_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timing',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
