# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2', '0006_auto_20180121_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateField(null=True),
        ),
    ]
